global:
  applicationName: bem
  env: prod
createStorageClass: true
basePath:
  /var/k8s
volumes:
  - type: repository
    capacity: 10Gi
    replicationPerNode: 4
  - type: logs
    capacity: 10Gi
    replicationPerNode: 4
  - type: database
    capacity: 10Gi
    replicationPerNode: 4
nodes:
  - node1
  - node2
  - node3
