{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bloomreach.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ $fullName }}-cms"
  labels:
    usage: cms
    {{- include "bloomreach.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: SERVERID
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/upstream-fail-timeout: 1s
    nginx.ingress.kubernetes.io/upstream-max-fails: "250"
    {{- range $key, $value := $.Values.ingress.cms.additionalAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{- if $.Values.ingress.cms.tls }}
  tls:
    - hosts:
        - {{ $.Values.ingress.cms.host | quote }}
      {{- if $.Values.ingress.cms.secretName }}
      secretName: {{ $.Values.ingress.cms.secretName }}
      {{- end }}
{{- end }}
  rules:
    - host: {{ $.Values.ingress.cms.host | quote }}
      http:
        paths:
          - path: "/cms"
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          - path: "/site"
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
---
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ $fullName }}-site"
  labels:
    usage: site
    {{- include "bloomreach.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/site/$1"
    {{- range $key, $value := $.Values.ingress.site.additionalAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if $.Values.ingress.site.tls }}
  tls:
    - hosts:
        - {{ $.Values.ingress.site.host | quote }}
      {{- if $.Values.ingress.site.secretName }}
      secretName: {{ $.Values.ingress.site.secretName }}
  {{- end }}
  {{- end }}
  rules:
    - host: {{ $.Values.ingress.site.host | quote }}
      http:
        paths:
          - path: "/(.*)"
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
{{- end }}
