{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bloomreach.serviceAccountName" . }}
  labels:
{{ include "bloomreach.labels" . | nindent 4 }}
{{- end -}}
