apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bloomreach.fullname" . }}
  labels:
    {{- include "bloomreach.labels" . | nindent 4 }}
spec:
  serviceName: {{ $.Release.Name }}
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bloomreach.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bloomreach.selectorLabels" . | nindent 8 }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bloomreach.serviceAccountName" . }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range  $key, $value := $.Values.env }}
            - name: {{ $key | quote}}
              value: {{  $value | quote }}
             {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
