apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bloomreach.fullname" . }}
  labels:
    {{- include "bloomreach.labels" . | nindent 4 }}
spec:
  serviceName: {{ $.Release.Name }}
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bloomreach.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    {{- range $.Values.volumeClaims }}
    - metadata:
        name: {{ .name | quote}}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .storageClassName }}
        selector:
          matchLabels:
            application: {{ $.Values.global.applicationName | quote}}
            env: {{ $.Values.global.env | quote  }}
            type: {{ .type | quote}}
        resources:
          requests:
            storage: {{ .size | quote}}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "bloomreach.selectorLabels" . | nindent 8 }}
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bloomreach.serviceAccountName" . }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range  $.Values.envFromSecert }}
            - name: {{ .name | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName | quote}}
                  key: {{ .secretKey | quote}}
            {{- end }}
            {{- range  $.Values.envFromConfigMap }}
            - name: {{ .name | quote }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .configmapName | quote}}
                  key: {{ .configmapKey | quote}}
            {{- end }}
            {{- range  $key, $value := $.Values.env }}
            - name: {{ $key | quote}}
              value: {{  $value | quote }}
             {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            {{- range $.Values.volumeClaims }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
