global:
  env: "prod"
  applicationName: "bem"

replicaCount: 1

image:
  repository: openweb/hippo-cms-ootb
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  TZ: "Europe/Amsterdam"
  MAX_RAM_PERCENTAGE: "60"
  EXTRA_OPTS: "-XX:MaxMetaspaceSize=200m -XX:MaxDirectMemorySize=100m"

envFromSecert: []
#  - name: "DB_PASS"
#    secretName: "bloomreach-secrets"
#    secretKey: "databasePassword"

envFromConfigMap: []
#  - name: "ENV_VAR_NAME"
#    configmapName: "configmap-name"
#    configmapKey: "configmap-key"

livenessProbe:
  path: /cms/ping/
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 5
readinessProbe:
  path: /cms/ping/
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 5

terminationGracePeriodSeconds: 30

volumeClaims:
  - name: "repository"
    type: "repository"
    mountPath: "/usr/local/repository/"
    storageClassName: "local-storage"
    size: "10G"
  - name: "bem-logs"
    type: "logs"
    mountPath: "/usr/local/tomcat/logs"
    storageClassName: "local-storage"
    size: "10G"

mountFileFromSecrect: []
#  - name: "some-setting"
#    fileName: "filename.txt"
#    folder: "/path/to/folder"
#    secretName: "secret-name"
#    secretKey: "secret-key"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: SERVERID
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/upstream-fail-timeout: 1s
    nginx.ingress.kubernetes.io/upstream-max-fails: "250"
  hosts:
    - host: chart-example.local
      paths:
        - "/cms"
        - "/site"

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 3000m
    memory: 1024Mi
  requests:
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
